change nav into dropdown using <details>
kevquirk/simple.css pull request #100
Opened 2022-08-03 12:36 UTC by yapkahkeat0711

2022-08-03 13:04 UTC, lkhrs requested changes
I appreciate you addressing my concerns in #99, however these changes need some work on the design and markup. I left comments in the review.

2022-08-03 13:04 UTC, lkhrs commented on index.html
> +		<details>
Multiple dropdown menus cause undesirable one menu per line

2022-08-03 13:04 UTC, lkhrs commented on simple.css
> +}
If no CSS changes have been made, better to discard all than submit empty lines.

Dropdown menus could use better styling in header (see: one menu per line issue, could use slightly better design to make it look like a menu)

2022-08-04 18:55 UTC, closed without merging

2022-08-04 19:00 UTC, kevquirk commented
I have no idea what the point of this PR is, and you're not communicating. Closing this PR down.

2022-08-04 19:29 UTC, yapkahkeat0711 commented
i am trying to fix the problem stated and make the navigation bar become more reliable.

2022-08-04 21:12 UTC, kevquirk commented
The nav bar is supposed to be simple, then you cam build upon it as you see fit.

2022-08-05 14:24 UTC, yapkahkeat0711 commented
Oh ok. I will try it.