Improve details and change background to background-color
kevquirk/simple.css pull request #110
Opened 2022-08-21 15:51 UTC by wahyuwiyoko

Instead of changing the padding on `summary`, it's good to change the padding directly on `details` to reduce the code, it has the same effect.

Using `background` (shorthand) just for color it's really not a good practice, since it will add the rest of  `background` property **by default** with the value such as `background-attachment`, `background-clip`, `background-origin`, `background-repeat`, `background-size`.

2022-08-21 18:02 UTC, lkhrs commented
I agree and like the `background-color` change.

I need to test the padding change on summary and details. Off the bat, this change reduces the tap target area, but we need to see if it's a significant reduction in usability and doesn't cause new issues. 

One issue to check for is if the text in summary isn't long enough to fill the block, the tap target might only be as large as the text.

2022-08-21 18:45 UTC, wahyuwiyoko commented
Well, I had tested the padding of details and works well like the original style.

But have one problem, you will see the overflow word if the `summary` text are long more than `details` size.
![before](https://user-images.githubusercontent.com/111651479/185806111-432924ee-b8c7-4692-8d8a-3bd8d2c88cd2.PNG)

I tested using `word-wrap: break-word` could fix this:
![after](https://user-images.githubusercontent.com/111651479/185806159-3affe24e-3695-4a68-a801-579ebb3cd996.PNG)

Should I add `word-wrap: break-word`?

2022-08-27 19:05 UTC, lkhrs requested changes
After some testing, the tap target for `summary` is too small. We need a minimum of 48px width and height on `summary` when a `details` element is open or closed. 

I think this is the best way to solve that:
- set padding to `0.7rem 1rem` on `details` and `summary`
- set margin to `-0.7rem -1rem` on `summary`

> Should I add `word-wrap: break-word`?

Let's use `word-break: break-all` instead, so the first line of a long continuous line of text stays on the same line as the `details` chevron.

2022-08-28 04:03 UTC, wahyuwiyoko commented
Done @lkhrs

2022-08-28 06:19 UTC, lkhrs approved these changes

2022-08-28 06:20 UTC, merged