Add styling for dialog elements
kevquirk/simple.css pull request #140
Opened 2023-04-06 17:25 UTC by pietvanzoen

2023-04-06 18:22 UTC, lkhrs requested changes
Thanks for working on this. I noted a minor formatting issue.

2023-04-06 18:22 UTC, lkhrs commented on simple.css
> +
Let's remove the blank lines on line 630 and 648.

2023-04-06 18:28 UTC, waldyrious commented
For comparison:

| Before | After |
| ------ | ----- |
| ![Screen Shot 2023-04-06 at 19 12 15](https://user-images.githubusercontent.com/478237/230463687-ed374ac7-85cb-48d5-9673-e00853d4b2dd.png) | ![Screen Shot 2023-04-06 at 19 13 40](https://user-images.githubusercontent.com/478237/230463695-2430d049-f82b-4b09-84c6-942858833369.png) |

(Are the Netlify preview links configurable? I wonder if there's a way to have an additional link that would essentially render the new `index.html` with the old `simple.css`, to allow for convenient before/after comparison like the above.)

2023-04-06 18:42 UTC, lkhrs commented
> (Are the Netlify preview links configurable? I wonder if there's a way to have an additional link that would essentially render the new `index.html` with the old `simple.css`, to allow for convenient before/after comparison like the above, which I had to set up by hand.)

The latest commit to `main` is viewable on the CDN subdomain: https://cdn.simplecss.org

2023-04-08 21:10 UTC, pietvanzoen commented
@lkhrs No problem and thanks for the prompt review. Removed the whitespace.

2023-04-09 01:37 UTC, lkhrs approved these changes

2023-04-09 01:37 UTC, merged

2023-04-09 22:32 UTC, waldyrious commented
> The latest commit to `main` is viewable on the CDN subdomain: [cdn.simplecss.org](https://cdn.simplecss.org/)

Thanks for that info, I wasn't aware of it. Still, while that may be sufficient in many cases, it doesn't include HTML markup that is introduced/edited in a PR. In this case, for example, there would be no dialog element in the `main`-based demo, so a before/after comparison would not be possible without extra work.